private_key_path: ./inet256_private1.pem

api_addr: 127.0.0.1:25601

networks:
- kad+sr 

transports:
- udp: "0.0.0.0:44444"
  nat_upnp: false

peers:
- id: TryuCcgaaslRvLvOYRb9FeBLa-xS92Wk4aaapaAq8eQ
  addrs:
  - noise+udp://TryuCcgaaslRvLvOYRb9FeBLa-xS92Wk4aaapaAq8eQ@127.0.0.1:44445
