private_key_path: ./inet256_private2.pem

api_addr: 127.0.0.1:25602

networks:
- onehop

transports:
- udp: "0.0.0.0:44445"
  nat_upnp: false

peers:
- id: xSqGrMo8gJKqXymZ-huFL8D6mJ6J_ZUM8eEDQxwiPiY
  addrs:
  - noise+udp://xSqGrMo8gJKqXymZ-huFL8D6mJ6J_ZUM8eEDQxwiPiY@127.0.0.1:44444
