private_key_path: ./inet256_private1.pem

api_addr: 127.0.0.1:25601

networks:
- onehop

transports:
- udp: "0.0.0.0:44444"
  nat_upnp: false

peers:
- id: 7vzW5aTcTH_m2d9wEE3rPjOl44kRe0MzjirWQYEPuxc
  addrs:
  - noise+udp://7vzW5aTcTH_m2d9wEE3rPjOl44kRe0MzjirWQYEPuxc@127.0.0.1:44445
